configoptions="
--disable-short-tags \
--enable-bcmath \
--enable-cli \
--enable-cgi \
--enable-calendar \
--enable-cli \
--enable-exif \
--enable-fpm \
--enable-ftp \
--enable-intl \
--enable-intl \
--enable-mbstring \
--enable-pcntl \
--enable-soap \
--enable-sockets \
--enable-wddx \
--enable-zip \
--with-curl \
--with-freetype-dir=/usr/include/freetype2 \
--with-gd \
--with-gettext \
--with-jpeg-dir \
--with-layout=GNU \
--with-libzip \
--with-mysqli \
--with-openssl \
--with-pdo-mysql \
--with-png-dir \
--with-readline \
--with-xsl \
--with-zlib \
--with-pear
"